language: php

php:
  - 7.0
  - 7.1
  - hhvm

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
